#!/bin/zsh

. ./.env

MODULE=$1
REMOTE_STATE_KEY=`echo TF_VAR_${MODULE}_remote_state_key`

cd $MODULE

terraform remote config \
    -backend=s3 \
    -backend-config="bucket=${TF_VAR_remote_state_bucket}" \
    -backend-config="key=${(P)REMOTE_STATE_KEY}" \
    -backend-config="region=${TF_VAR_aws_region}"

terraform apply
